# Site
repository: Azmmat/Azmmat.github.io
favicon: images/favicon.ico

# Personal info
name: Azmat 
title: Cyber Security Specialist
# email: info@azmatnaseem.com
# website: https://www.azmatnaseem.com

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: ABC
github_username:  ABC
# dribbble_username: jekyll
facebook_username: ABC
# flickr_username: jekyll
# instagram_username: ABC
linkedin_username: ABC
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.JPG
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Azmat .............................................................

  I am most skilled in: <mark>Security</mark> <mark>Networks</mark> and <mark>NGFW</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About My Skills
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in Web and Software development some of my other interests, **Skills** and **Hobbies** are:
   - [Reading](https://openlibrary.org/)
   - [Gaming](https://www.miniclip.com/)
   - [Coding](https://www.youtube.com/c/Freecodecamp/videos)  
   
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
