# Site
repository: Azmmat/Azmmat.github.io
favicon: images/favicon.ico

# Personal info
name: Azmat Naseem
title: Web Developer
email: azmatnaseem45@gmail.com
website: https://azmmat.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: AzmatNaseem
github_username:  Azmmat
# dribbble_username: jekyll
facebook_username: AzmmatNaseem
# flickr_username: jekyll
instagram_username: AzmatNaseem
linkedin_username: AzmatNaseem
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Azmat and I'm a junior web developer.I also have experience making mobile apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>JavaScript</mark> and <mark>JavaScript</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in web and software development some of my other interests and hobbies are:
   - Reading
   - Gaming
   - Cooking
   
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
