# Site
repository: Azmmat/Azmmat.github.io
favicon: images/favicon.ico

# Personal info
name: Azmat Naseem
title: Web Developer
# email: azmatnaseem45@gmail.com
website: www.azmatnaseem.com

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: AzmatNaseem
github_username:  Azmmat
# dribbble_username: jekyll
facebook_username: AzmmatNaseem
# flickr_username: jekyll
# instagram_username: AzmatNaseem
linkedin_username: AzmatNaseem
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.JPG
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Azmat and I'm a junior web developer.I also have experience making mobile apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>C#</mark>, <mark>.NET</mark> and <mark>JavaScript</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About My Skills
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in web and software development some of my other interests, **Skills** and *hobbies* are:
   - Reading
   - Gaming
   - [Coding](https://www.youtube.com/watch?v=vtg4o__aRMg)  
   
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
